services:
  api-tests-dev:
    build: .
    image: emilsriekstins/api-tests
    container_name: api-tests-dev
    # network_mode: host
    volumes:
      - $PWD/test-reports/dev:/api-tests/mochawesome-report
    command: run BOOKS BOOKS_DEV
    networks:
      - sample-book-app-network-compose
  api-tests-stg:
    build: .
    image: emilsriekstins/api-tests
    container_name: api-tests-stg
    # network_mode: host
    volumes:
      - $PWD/test-reports/stg:/api-tests/mochawesome-report
    command: run BOOKS BOOKS_STG
    networks:
      - sample-book-app-network-compose
  api-tests-prd:
    build: .
    image: emilsriekstins/api-tests
    container_name: api-tests-prd
    # network_mode: host
    volumes:
      - $PWD/test-reports/prd:/api-tests/mochawesome-report
    command: run BOOKS BOOKS_PRD
    networks:
      - sample-book-app-network-compose

networks:
  sample-book-app-network-compose:
    external: true # means that this network does not need to be created, but will attach to already existing one

# Execution form terminal
# docker build -t api-tests .
# docker run --rm --network=sample-book-app-network -v "$PWD:/api-tests/mochawesome-report" api-tests run BOOKS BOOKS_LOCAL


